<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JobType extends Model
{
    protected $guarded =[];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($vacancy){
            $relationsMethods = ['vacancy'];
            foreach ($relationsMethods as $relationsMethod){
                if ($vacancy->$relationsMethod()->count() > 0){
                    return false;
                }
            }
        });
    }

    public function vacancy()
    {
        return $this->belongsTo(Vacancy::class,'id','job_type_id');
    }
}
